# Generated by Django 5.0.1 on 2024-02-02 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_app', '0002_event_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='description',
        ),
        migrations.CreateModel(
            name='MedicineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('doses', models.IntegerField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='medicine_app.medicine')),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
